### ISSUE TITLE
after recent update - no longer working

### ISSUE THREAD

**Issue by ohadlevy** [ProudElm/packaging_solaredgeoptimizers#1]
Hello,

I've upgraded to 1.2.0 (from1.14) and i see the following error in my logs:
`[custom_components.solaredgeoptimizers.sensor] Error fetching SolarEdgeOptimizer data: 'IST'`

all the sensors are in unknown state.

**Comment by ProudElm** [comment]
What timezone are you from? IST can be several i'm researching..

**Comment by ohadlevy** [comment]
Sorry, that's Israel

**Comment by ProudElm** [comment]
Ok thanx.. Im trying to skip the hole timezone thing.. ;-)
